name: Test REFRESH_TOKEN

on:
  push:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Check REFRESH_TOKEN Availability
      run: |
        echo "Checking if REFRESH_TOKEN is set..."
        if [ -z "${{ secrets.REFRESH_TOKEN }}" ]; then
          echo "REFRESH_TOKEN is not set or is empty"
          exit 1
        else
          echo "REFRESH_TOKEN is set"
        fi

    - name: Make API Call with REFRESH_TOKEN
      env:
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: |
        response=$(curl -k --location "https://example.com/api" \
          --header "Authorization: Bearer $REFRESH_TOKEN")
        echo $response
