- name: Get the list of changed SQL files
  id: changed_files
  run: |
    # Check if there are at least 2 commits
    if [ $(git rev-list --count HEAD) -gt 1 ]; then
      # List of changed SQL files
      changed_files=$(git diff --name-only HEAD~1 HEAD | grep '^domain_1/.*\.sql$' || true)
      echo "Changed files: $changed_files"

      # Initialize a variable to track existing SQL files
      existing_files=""
      
      for file in $changed_files; do
        # Extract the path relative to domain_1
        relative_file=$(echo "$file" | sed 's|^domain_1/||')
        
        # Check if the file existed in the previous commit
        if git ls-tree --name-only HEAD~1 | grep -q "^${relative_file}"; then
          existing_files+="${file} "
        fi
      done
      
      echo "EXISTING_CHANGED_FILES=${existing_files}" >> $GITHUB_ENV
    else
      echo "No previous commit to compare with." > changed_files.txt
      echo "EXISTING_CHANGED_FILES=" >> $GITHUB_ENV
    fi
    echo "Changed files: ${existing_files}"
