name: Print Changed Files

on:
  push:
    branches:
      - main  # You can change this to any branch you want to monitor

jobs:
  print-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only HEAD~1 HEAD > changed_files.txt
          cat changed_files.txt

      - name: Display changed files
        run: |
          echo "Changed files:"
          cat changed_files.txt
