name: CI Pipeline

on:
  push:
    paths:
      - 'domain_1/**'

jobs:
  process_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history to ensure HEAD^ works

    - name: Fetch Full History
      run: git fetch --unshallow || true

    - name: Determine Changed SQL Files
      id: changed_files
      run: |
        # Get the latest commit and its parent
        latest_commit=$(git rev-parse HEAD)
        parent_commit=$(git rev-parse HEAD^)
        
        # Ensure we have valid commits to compare
        if [ -z "$latest_commit" ] || [ -z "$parent_commit" ]; then
          echo "Error: Unable to retrieve commits."
          exit 1
        fi

        # Get the list of changed SQL files
        changed_files=$(git diff --name-only --diff-filter=M $parent_commit $latest_commit domain_1/ | grep '\.sql$')
        echo "CHANGED_FILES=$changed_files" >> $GITHUB_ENV

    - name: Log Changed Files
      run: |
        echo "Changed files:"
        echo "$CHANGED_FILES"
