name: Create and Activate Pipeline Version

on:
  push:
    paths:
      - 'domain_1/**'

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Read Configuration
      id: read_config
      run: |
        if [ -f domain_1/config.txt ]; then
          domain_id=$(grep 'domainid=' domain_1/config.txt | cut -d'=' -f2)
          host=$(grep 'host=' domain_1/config.txt| cut -d'=' -f2)
          echo "DOMAIN_ID=$domain_id" >> $GITHUB_ENV
          echo "HOST=$host" >> $GITHUB_ENV
        else
          echo "Configuration file not found!"
          exit 1
        fi

    - name: Get Authentication Token
      id: auth
      env:
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: |
        response=$(curl -k --location "https://${{ env.HOST }}/v3/security/token/access" \
          --header "Authorization: Basic $REFRESH_TOKEN")
        echo $response
        token=$(echo $response | jq -r '.result.authentication_token')
        echo "TOKEN=$token" >> $GITHUB_ENV
        echo $token
        echo $REFRESH_TOKEN



