name: Pipeline Update

on:
  push:
    branches:
      - main
    paths:
      - 'domain_1/**'

jobs:
  update_pipelines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Changed Files
        run: |
          git fetch origin
          changed_files=$(git diff --name-only --diff-filter=d "${FIRST_COMMIT}" "${LAST_COMMIT}" | grep '^domain_1/.*\.sql$' || true)
          echo "Changed files: $changed_files"
          echo "CHANGED_FILES=${changed_files}" >> $GITHUB_ENV

      - name: Get Pipelines
        run: |
          pipelines=$(curl -k --location "https://att-iwx-ci-cd.infoworks.technology/v3/domains/${DOMAIN_ID}/pipelines" \
            --header "Authorization: Bearer ${TOKEN}")
          echo "$pipelines" | jq -r '.result[] | "\(.name) \(.id)"' > pipelines.txt

      - name: Process Changed Files
        run: |
          for file in $CHANGED_FILES; do
            pipeline_name=$(basename "$file" .sql)
            pipeline_id=$(grep "$pipeline_name" pipelines.txt | awk '{print $2}')

            if [ -n "$pipeline_id" ]; then
              query=$(base64 < "$file")
              create_response=$(curl -k --request POST \
                --url "https://att-iwx-ci-cd.infoworks.technology/v3/domains/${DOMAIN_ID}/pipelines/$pipeline_id/versions" \
                --header "Content-Type: application/json" \
                --header "Authorization: Bearer ${TOKEN}" \
                --data "{\"pipeline_id\": \"$pipeline_id\", \"type\": \"sql\", \"query\": \"$query\"}")
              
              pipeline_version_id=$(echo $create_response | jq -r '.result.id')
              
              curl -k --request POST \
                --url "https://att-iwx-ci-cd.infoworks.technology/v3/domains/${DOMAIN_ID}/pipelines/$pipeline_id/versions/$pipeline_version_id/set-active" \
                --header "Authorization: Bearer ${TOKEN}"
            else
              echo "Pipeline ID not found for $pipeline_name"
            fi
          done
